# This file was generated by GoReleaser. DO NOT EDIT.
cask "dgrkt" do
  name "dgrkt"
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/TPIsoftwareOSPO/digiRocket"
  version "1.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dgrkt"

  on_macos do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_amd64.tar.gz"
      sha256 "45022719e7fdbae000ec9595411486bebf4e28057df43f88e9cdd97cab935784"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_arm64.tar.gz"
      sha256 "f3561c2d4d3195ab7fa26fd063b4fb740e83b177cc47137a99791170c244fdb7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_amd64.tar.gz"
      sha256 "37fed38f03a7cfd95793d45e0291553b76eaea5f7fc501123d1fee01aa2cb124"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_arm64.tar.gz"
      sha256 "4b41aeb5fb3411aecd74e2d03ffcb78caf0c57b4e2fadbf1a71f94b743302ab3"
    end
  end

  # No zap stanza required
end
