# This file was generated by GoReleaser. DO NOT EDIT.
cask "dgrkt" do
  name "dgrkt"
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/TPIsoftwareOSPO/digiRocket"
  version "1.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dgrkt"

  on_macos do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_amd64.tar.gz"
      sha256 "805c063ca4b3c6351b59d2c2604be238c2769de61f9618bd7e0d433348a07848"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_arm64.tar.gz"
      sha256 "1ce0ac2becbf047a8c365caa1433d98945ca2ae35871adf29a8d9293c5875e7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_amd64.tar.gz"
      sha256 "cbc1532fc1cf533b9a40e1c5f6f6e3e8a7a019b69574b9340baa49ac2f277c6a"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_arm64.tar.gz"
      sha256 "b4c648e69f1300eea1f1a13fd56650f5e0bc80e40853635f708bf8f658d596b5"
    end
  end

  # No zap stanza required
end
