# This file was generated by GoReleaser. DO NOT EDIT.
cask "dgrkt" do
  name "dgrkt"
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/TPIsoftwareOSPO/digiRocket"
  version "1.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dgrkt"

  on_macos do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_amd64.tar.gz"
      sha256 "28baea606e247355fab41a4b37c2bc3fb76947c827abf049cccc5d38efa651d3"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_darwin_arm64.tar.gz"
      sha256 "de5003c92dbba8d7e6a752a227bed6ff06db496f665f3bcad98a5b3131bc114d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_amd64.tar.gz"
      sha256 "370516c6a94197e0a6a07e40bf95dd69b3a10505290b4f26c5cce80f80c2c17e"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/digiRocket/releases/download/v#{version}/digiRocket_#{version}_linux_arm64.tar.gz"
      sha256 "3e383d0a91b016cf3ef2e66e2f7385f435486b19051c286d879f65d345daab78"
    end
  end

  # No zap stanza required
end
