# This file was generated by GoReleaser. DO NOT EDIT.
cask "quickstart" do
  name "quickstart"
  desc "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
  homepage "https://github.com/TPIsoftwareOSPO/quickstart"
  version "1.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "quickstart"

  on_macos do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/quickstart/releases/download/v#{version}/quickstart_#{version}_darwin_amd64.tar.gz"
      sha256 "9e2d1710a7da478b88622986d3b2deb1ce75d9953d786bddd0992838587e8a5d"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/quickstart/releases/download/v#{version}/quickstart_#{version}_darwin_arm64.tar.gz"
      sha256 "5f84d63b6f6c1c004acc27caa76aad5a0fc234a2048d9d6de242496ff328ff21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/TPIsoftwareOSPO/quickstart/releases/download/v#{version}/quickstart_#{version}_linux_amd64.tar.gz"
      sha256 "bc46a8ebd92a5bc1e705e0c3a8e26efbab73730ef7afb3e3a2d4df1e2141980d"
    end
    on_arm do
      url "https://github.com/TPIsoftwareOSPO/quickstart/releases/download/v#{version}/quickstart_#{version}_linux_arm64.tar.gz"
      sha256 "586a43652d7b6f3ce2962b5bb64022a0bd6d4f3396272945aa96f7ba0557e58a"
    end
  end

  # No zap stanza required
end
